# Generated by Django 4.2.5 on 2023-11-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('First Course', 'First Course'), ('Main', 'Main'), ('Dessert', 'Dessert')], max_length=100, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(verbose_name='Time (min)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.CharField(max_length=1000, verbose_name='Steps'),
        ),
    ]
